version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/booking-api
hooks:
  BeforeInstall:
    - location: deploy/BeforeInstall.sh
  AfterInstall:
    - location: deploy/AfterInstall.sh
  ApplicationStart:
    - location: deploy/ApplicationStart.sh
  ValidateService:
    - location: deploy/ValidateService.sh
