imports:
    - { resource: parameters.php }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            service:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   default
        entity_managers:
            default:
                auto_mapping: true
                connection:   service
                mappings:
                    FOSUserBundle: ~
                    DBUserBundle: ~
                    FOSOAuthServerBundle: ~
                    DBServiceBundle: ~
                dql:
                    datetime_functions:
                        date_format: DoctrineExtensions\Query\Postgresql\DateFormat
                        at_time_zone: DoctrineExtensions\Query\Postgresql\AtTimeZoneFunction
                    string_functions:
                        str_to_date: DoctrineExtensions\Query\Postgresql\StrToDate
                        count_filter: DoctrineExtensions\Query\Postgresql\CountFilterFunction
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
    #debug for mail
    delivery_address:  "%mailer_debug%"

nelmio_api_doc:
    sandbox:
        authentication:
            name: access_token
            type: bearer 
            delivery: query

sensio_framework_extra:
    view:
        annotations: false
    
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
    routing_loader:
        default_format: json
        include_format: false
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: DB\UserBundle\Entity\User

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['*']
        expose_headers: ['*']
        max_age: 3600
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
            hosts: ['^api\.']

stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
    orm:
        service:
            tree: true
            timestampable: true
            sluggable: true

fos_oauth_server:
    db_driver: orm
    client_class:        DB\UserBundle\Entity\Client
    access_token_class:  DB\UserBundle\Entity\AccessToken
    refresh_token_class: DB\UserBundle\Entity\RefreshToken
    auth_code_class:     DB\UserBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager
