imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [nested,buffered]
        nested:
            type:  stream
            path:  "%custom_logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: "%mailer_develloper%"
            to_email:   "%mailer_develloper%"
            subject:    An Error Occurred!
            level:      debug
            path:   "%custom_logs_dir%/%kernel.environment%.log"
